// 
const DATA = [
  {
    id: 1,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",
    author: "Chinua Achebe",
    country: "Nigeria",
    img: "/assets/images/products/things-fall-apart.jpg",
    link: "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
    price: 209,
    title: "Things Fall Apart",
    year: 1958,
  },
  {
    id: 2,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",
    author: "Hans Christian Andersen",
    country: "Denmark",
    img: "/assets/images/products/fairy-tales.jpg",
    price: 784,
    title: "Fairy tales",
    year: 1836,
  },
  {
    id: 3,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",

    author: "Dante Alighieri",
    country: "Italy",
    img: "/assets/images/products/the-divine-comedy.jpg",
    language: "Italian",
    link: "https://en.wikipedia.org/wiki/Divine_Comedy\n",
    price: 928,
    title: "The Divine Comedy",
    year: 1315,
  },
  {
    id: 4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",
    author: "Unknown",
    country: "Sumer and Akkadian Empire",
    img: "/assets/images/products/the-epic-of-gilgamesh.jpg",
    language: "Akkadian",
    link: "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
    price: 160,
    title: "The Epic Of Gilgamesh",
    year: -1700,
  },
  {
    id: 5,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",
    author: "Unknown",
    country: "Achaemenid Empire",
    img: "/assets/images/products/the-book-of-job.jpg",
    language: "Hebrew",
    link: "https://en.wikipedia.org/wiki/Book_of_Job\n",
    price: 176,
    title: "The Book Of Job",
    year: -600,
  },
  {
    id: 6,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",
    author: "Unknown",
    country: "India/Iran/Iraq/Egypt/Tajikistan",
    img: "/assets/images/products/one-thousand-and-one-nights.jpg",
    language: "Arabic",
    link: "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
    price: 288,
    title: "One Thousand and One Nights",
    year: 1200,
  },
  {
    id: 7,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",
    author: "Unknown",
    country: "Iceland",
    img: "/assets/images/products/njals-saga.jpg",
    language: "Old Norse",
    link: "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
    price: 384,
    title: "Nj\u00e1l's Saga",
    year: 1350,
  },
  {
    id: 8,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",
    author: "Jane Austen",
    country: "United Kingdom",
    img: "/assets/images/products/pride-and-prejudice.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    price: 226,
    title: "Pride and Prejudice",
    year: 1813,
  },
  {
    id: 9,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",
    author: "Honor\u00e9 de Balzac",
    country: "France",
    img: "/assets/images/products/le-pere-goriot.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
    price: 443,
    title: "Le P\u00e8re Goriot",
    year: 1835,
  },
  {
    id: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",
    author: "Samuel Beckett",
    country: "Republic of Ireland",
    img: "/assets/images/products/molloy-malone-dies-the-unnamable.jpg",
    language: "French, English",
    link: "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
    price: 256,
    title: "Molloy, Malone Dies, The Unnamable, the trilogy",
    year: 1952,
  },
  {
    id: 11,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",
    author: "Giovanni Boccaccio",
    country: "Italy",
    img: "/assets/images/products/the-decameron.jpg",
    language: "Italian",
    link: "https://en.wikipedia.org/wiki/The_Decameron\n",
    price: 1024,
    title: "The Decameron",
    year: 1351,
  },
  {
    id: 12,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",
    author: "Jorge Luis Borges",
    country: "Argentina",
    img: "/assets/images/products/ficciones.jpg",
    language: "Spanish",
    link: "https://en.wikipedia.org/wiki/Ficciones\n",
    price: 224,
    title: "Ficciones",
    year: 1965,
  },
  {
    id: 13,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",
    author: "Emily Bront\u00eb",
    country: "United Kingdom",
    img: "/assets/images/products/wuthering-heights.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
    price: 342,
    title: "Wuthering Heights",
    year: 1847,
  },
  {
    id: 14,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",
    author: "Albert Camus",
    country: "Algeria, French Empire",
    img: "/assets/images/products/l-etranger.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
    price: 185,
    title: "The Stranger",
    year: 1942,
  },
  {
    id: 15,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",
    author: "Paul Celan",
    country: "Romania, France",
    img: "/assets/images/products/poems-paul-celan.jpg",
    language: "German",
    link: "\n",
    price: 320,
    title: "Poems",
    year: 1952,
  },
  {
    id: 16,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",
    author: "Louis-Ferdinand C\u00e9line",
    country: "France",
    img: "/assets/images/products/voyage-au-bout-de-la-nuit.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n",
    price: 505,
    title: "Journey to the End of the Night",
    year: 1932,
  },
  {
    id: 17,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis labore, minima animi odio qui quos praesentium sequi debitis officiis, ad repudiandae quasi cumque dolor ullam nisi possimus laborum ex adipisci facilis hic deleniti natus ducimus tempora! Esse quia veniam veritatis!",
    author: "Miguel de Cervantes",
    country: "Spain",
    img: "/assets/images/products/don-quijote-de-la-mancha.jpg",
    language: "Spanish",
    link: "https://en.wikipedia.org/wiki/Don_Quixote\n",
    price: 1056,
    title: "Don Quijote De La Mancha",
    year: 1610,
  },
];

export default DATA;
